INSERT INTO DOMINIOS VALUES
('COLORES', 'RO', 'ROJO'),
('COLORES', 'AZ', 'AZUL'),
('COLORES', 'NE', 'NEGRO'),
('COLORES', 'BL', 'BLANCO'),
('COLORES', 'GR', 'GRIS'),
('COLORES', 'AM', 'AMARILLO');

INSERT INTO DOMINIOS VALUES
('MARCAS', 'CHEV', 'CHEVROLET'),
('MARCAS', 'REN', 'RENAULT'),
('MARCAS', 'KIA', 'KIA'),
('MARCAS', 'VOL', 'VOLKSWAGEN'),
('MARCAS', 'FOR', 'FORD'),
('MARCAS', 'MAZ', 'MAZDA'),
('MARCAS', 'SUB', 'SUBARU'),
('MARCAS', 'BMW', 'BMW'),
('MARCAS', 'FER', 'FERRARI'),
('MARCAS', 'JAG', 'JAGUAR'),
('MARCAS', 'CHA', 'CHANGAN'),
('MARCAS', 'LAM', 'LAMBORGHINI'),
('MARCAS', 'HON', 'HONDA'),
('MARCAS', 'SUZ', 'SUZUKI'),
('MARCAS', 'CHE', 'CHERY'),
('MARCAS', 'NIS', 'NISSAN'),
('MARCAS', 'MG', 'MORRIS GARAGES'),
('MARCAS', 'MER', 'MERCEDES BENZ');

INSERT INTO DOMINIOS VALUES
('TIPOS_VEHICULO', 'AUT', 'AUTOMOVIL'),
('TIPOS_VEHICULO', 'CAM', 'CAMIONETA'),
('TIPOS_VEHICULO', 'CMO', 'CAMION'),
('TIPOS_VEHICULO', 'BUS', 'BUSETA');

INSERT INTO DOMINIOS VALUES
('TIPO_PERSONA', 'CLI', 'CLIENTE'),
('TIPO_PERSONA', 'MEC', 'MECANICO'),
('TIPO_PERSONA', 'ADM', 'ADMINISTRADOR');

INSERT INTO DOMINIOS VALUES
('ESPECIALIDAD', 'LAT', 'LATONERIA'),
('ESPECIALIDAD', 'ELE', 'ELECTRICO'),
('ESPECIALIDAD', 'ALIN', 'ALINEACION Y BALANCEO'),
('ESPECIALIDAD', 'ACE', 'CAMBIO DE ACEITE'),
('ESPECIALIDAD', 'SINC', 'SINCRONIZACIÓN'),
('ESPECIALIDAD', 'GRAL', 'MECANICA GENERAL'),
('ESPECIALIDAD', 'FRE', 'FRENOS');

